### ISSUE TITLE
Save button at each step

### ISSUE THREAD

**Issue by jsms90** [CYPIAPT-LNDSE/anxiety-ladder#10]
As a young person suffering from anxiety
I want to be able to save my steps as I go
So that I don't lose my progress if I stop half way through

**Comment by jsms90** [comment]
In trying to figure out how to do this, I realised that [the official guidelines](https://www.w3.org/TR/html5/forms.html#the-form-element) say that form elements cannot have form elements as descendants.

So I am going through [MDN on forms](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form) to figure out a workaround.

**Comment by jsms90** [comment]
The [best workaround](https://www.robin-drexler.com/2014/10/07/form-attribute.html) I can find at the moment uses the "form" attribute on an input field, for the inner forms.

**Comment by jsms90** [comment]
Instead of the challenge becoming un-editable once a user clicks 'save', [another option](http://parsleyjs.org/doc/examples/multisteps.html) for indicating that a challenge has been saved would be to change the background colour (or something else) when 'save' is clicked.

**Comment by ishiar** [comment]
when i introduced the narratives to my colleague, she was wondering if there could be a color code or a flag code or whatever that makes the YP understand in which ladder they actually are. so 'as a YP with anxiety, I would like to color code/flag code each goal, so that I know with which goal I am working whilst I am inserting the challenges.' so maybe whilst I am inserting a challenge that might be the shaded color of the ladder in the background whilst once I save it gets stronger and coincides with the color of the ladder in the overview of ladders in the start section?..

**Comment by jsms90** [comment]
@ishiar Each ladder will have its own separate page on the app, and the ladder/goal will have a title at the top of that screen, so I'm not sure there would be much confusion about which goal they are in.

We are putting screenshots into the readme, that should make the flow clearer #40 
And we will host the website asap, so you can start testing it out #42 

We can also show you what we've got so far when we see you at 2.30 :+1: :smile:

**Comment by jsms90** [comment]
Rather than having a "save" button, it would be better UX if any updates to the challenges were saved automatically whenever the user made an alteration.

This is a job for the backend implementation of this feature, so I am moving this to the next milestone. In terms of the prototype, changes will be saved once the user clicks the "complete ladder" button
