### ISSUE TITLE
isi input self help manual

### ISSUE THREAD

**Issue by ishiar** [CYPIAPT-LNDSE/anxiety-ladder#66]
@SavageWilliam pls find below some task descriptions, adapted from the analogue versions we use, in case they are of any help

1. Name a goal that you would like to achieve

2. Name a range of situations, activities, places or objects that you find challenging and that cause you distress.
For example, if your goal is related to using public transport by yourself, the list may include: waiting at a bus stop at a quiet time of the day, waiting at a bus stop at rush hour, checking in with my oyster card, getting on the bus and getting off after two bus stops, passing the train barriers, sitting on the train for two stops.

3. What did I observe and what did I learn?

**Comment by jsms90** [comment]
No. 1 is done

No. 2:
As a young person
I want to see some helpful hints on how to fill in the app
So that I don't get stuck on what to write / So that I explain my anxiety as fully as possible, to aid my next session and my own practices.

+ Change content (and size) of "description" placeholder

No. 3
For a future sprint
